
Vagrant.configure("2") do |config|
  
  config.vm.define "vm1" do |vm1|
    vm1.vm.box = "bento/ubuntu-20.04"
    vm1.vm.network "private_network", type: "dhcp", bridge: "wlp3s0"
    vm1.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end
    vm1.vm.provision "shell", path: "install_vm1.sh"
  end

  config.vm.define "vm2" do |vm2|
    vm2.vm.box = "bento/ubuntu-20.04"
    vm2.vm.network "private_network", type: "dhcp", bridge: "wlp3s0"
    vm2.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
    end
    vm2.vm.provision "shell", path: "install_vm2.sh"
  end

end
