version: '3.7'
services:
  web:
    build:
      context: ./web
    ports:
      - "8080:80"
    volumes:
      - ./app:/usr/share/nginx/html
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
