---
- name: Configure VM
  hosts: vmhost
  become: true
  tasks:
    - name: Update package cache
      apt:
        update_cache: yes

    - name: Install Apache
      apt:
        name: apache2
        state: present

    - name: Start Apache service
      service:
        name: apache2
        state: started

    - name: Create a user
      user:
        name: myuser
        state: present
        shell: /bin/bash
        groups: sudo
        create_home: true

    - name: Generate SSH key
      user:
        name: myuser
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: .ssh/id_rsa    

    - name: Add SSH key to the user
      authorized_key:
        user: myuser
        state: present
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"


