
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.network "private_network", type: "dhcp", bridge: "wlp3s0"
  config.vm.provider "virtualbox" do |vb| 
    vb.memory = 2048
    vb.cpus = 2
  end  
end
