
Vagrant.configure("2") do |config|

  config.vm.box = "bento/ubuntu-20.04"

  config.vm.box_check_update = false

  config.vm.provider "virtualbox" do |vb|
    vb.name = "ubuntu-20.04" 
    vb.memory = 2048
    vb.cpus = 1
  end  
  config.vm.network "forwarded_port", guest: 80, host: 8080
end
